### ISSUE TITLE
JFP version of this paper

### ISSUE THREAD

**Issue by shriram** [gallais/generic-syntax#7]
This is listed as the repo for the final version of the JFP paper:

https://gallais.github.io/publis.html

However, there *is* no JFP paper for this work. We've tried for well over a year now to contact all of you authors numerous times, creating a huge amount of work and overhead for us JFP staff. As of now, the paper has not been published and can't be.

I apologize for having to use this medium, but I'm hoping you are at least reading GitHub issues. What would it take to get one of you to respond to us?

**Comment by gallais** [comment]
Thanks for the reminder!

For those watching at home, it has finally landed: https://www.cambridge.org/core/journals/journal-of-functional-programming/article/abs/type-and-scopesafe-universe-of-syntaxes-with-binding-their-semantics-and-proofs/8A0865F34313BA65F4FE46D4522B4568
